### ISSUE TITLE
Multiple faces

### ISSUE THREAD

**Issue by Nicoleta-Blidaru** [HikkaV/Precise-face-alignment#2]
I was wondering if this alignment works well for multiple faces images as well? Because I see the image being rotated for one face, and I wonder how the rotation is being done when having multiple faces, because it's not seem to work okay.

**Comment by HikkaV** [comment]
This algorithm was produced to rotate only one face at time. I actually use
it as a preprocessing step in my application. You can crop the faces from
the image using the same dlib algorithm or some more advanced algorithms as
Yolo or ssd and after that align each face separately.
