### ISSUE TITLE
Rotation always to the right

### ISSUE THREAD

**Issue by davids890** [HikkaV/Precise-face-alignment#3]
Hi,
I tried to use the face_alignment.py code.
I copy the code to a notebook and add manually the image path and the rotation (1) and the show mode (0).

it seems like this model always rotate to the right (even thought it should rotate to the left in some specific cases)

Any advice will be welcome
Thanks

**Comment by HikkaV** [comment]
Hello, please send me the images you tested the application on, and I will
try to reproduce and fix the proem. Thanks
