### ISSUE TITLE
Error With Multiple Images

### ISSUE THREAD

**Issue by elliotmarks06** [HikkaV/Precise-face-alignment#4]
I want to run this for a folder full of images. When I put the photo folder directory as the path_to_load, there is an error.

``Traceback (most recent call last):
  File "run.py", line 8, in <module>
    face_alignment(args)
  File "/Users/elliotmarks/Precise-face-alignment/face_alignment.py", line 171, in face_alignment
    img = rotation_detection_opencv(img, args.rotation_mode, args.show)
  File "/Users/elliotmarks/Precise-face-alignment/face_alignment.py", line 130, in rotation_detection_opencv
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
cv2.error: OpenCV(4.0.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'``

When I run the example script, everything works fine. What am I doing wrong, and how do I fix it?

**Comment by HikkaV** [comment]
You are passing the directory, but the script expects you to pass the path to a single image. The script works only with one image at a time. If you want to run on every image in your folder, you will probably need to have a for loop in which you will iterate through the directory and pass images to the script. For this thing you will probably need to write a shell script (if you want to execute command from terminal with all the args) or write your own code on top of this repository.
